import "dotenv/config";

import bcrypt from "bcryptjs";
import { PrismaPg } from "@prisma/adapter-pg";
import { Prisma, PrismaClient } from "../src/generated/prisma/client.js";

const databaseUrl = process.env.DATABASE_URL;

if (!databaseUrl) {
  throw new Error("DATABASE_URL is required to run the CasaStudente seed.");
}

const prisma = new PrismaClient({
  adapter: new PrismaPg({ connectionString: databaseUrl }),
});

const DEMO_PASSWORD = "Demo123!";
const BCRYPT_COST = 12;
const now = new Date();

function daysAgo(days: number, hour = 10, minute = 0) {
  const date = new Date(now);
  date.setDate(date.getDate() - days);
  date.setHours(hour, minute, 0, 0);
  return date;
}

function daysFromNow(days: number, hour = 10, minute = 0) {
  const date = new Date(now);
  date.setDate(date.getDate() + days);
  date.setHours(hour, minute, 0, 0);
  return date;
}

function placeholderPhotos(slug: string) {
  return [1, 2, 3].map((index) => `https://placehold.co/1200x800/png?text=${slug}+${index}`);
}

function asJson(value: unknown) {
  return JSON.stringify(value);
}

async function clearDatabase() {
  await prisma.message.deleteMany();
  await prisma.conversationUser.deleteMany();
  await prisma.conversation.deleteMany();
  await prisma.payment.deleteMany();
  await prisma.leaseContract.deleteMany();
  await prisma.review.deleteMany();
  await prisma.notification.deleteMany();
  await prisma.savedSearch.deleteMany();
  await prisma.document.deleteMany();
  await prisma.journeyState.deleteMany();
  await prisma.onboardingProgress.deleteMany();
  await prisma.communityPost.deleteMany();
  await prisma.tenantScore.deleteMany();
  await prisma.insurancePolicy.deleteMany();
  await prisma.dispute.deleteMany();
  await prisma.housingGroupMember.deleteMany();
  await prisma.housingGroup.deleteMany();
  await prisma.telemetryEvent.deleteMany();
  await prisma.tourBooking.deleteMany();
  await prisma.uploadedFile.deleteMany();
  await prisma.roommateProfile.deleteMany();
  await prisma.session.deleteMany();
  await prisma.listing.deleteMany();
  await prisma.user.deleteMany();
}

async function main() {
  console.log("🌱 Seeding CasaStudente demo database...");

  await clearDatabase();

  const passwordHash = await bcrypt.hash(DEMO_PASSWORD, BCRYPT_COST);

  const users: Prisma.UserCreateManyInput[] = [
    {
      id: "user-student-giulia",
      email: "giulia.bartoletti@casastudente.demo",
      name: "Giulia Bartoletti",
      role: "student",
      passwordHash,
      verified: true,
      universityId: "UNIBO-IT-2026-0142",
      universityDocument: "https://placehold.co/800x1200/png?text=UNIBO+Badge+Giulia",
      profileComplete: true,
      onboardingComplete: true,
      campusId: "unibo-forli",
      locale: "it",
      stripeCustomerId: "cus_demo_giulia",
      createdAt: daysAgo(45, 9, 30),
      updatedAt: daysAgo(2, 18, 10),
    },
    {
      id: "user-student-lukas",
      email: "lukas.meyer@casastudente.demo",
      name: "Lukas Meyer",
      role: "student",
      passwordHash,
      verified: true,
      universityId: "ERASMUS-UNIBO-2026-008",
      universityDocument: "https://placehold.co/800x1200/png?text=Learning+Agreement+Lukas",
      profileComplete: true,
      onboardingComplete: true,
      campusId: "unibo-forli",
      locale: "en",
      stripeCustomerId: "cus_demo_lukas",
      createdAt: daysAgo(36, 11, 15),
      updatedAt: daysAgo(1, 15, 40),
    },
    {
      id: "user-landlord-francesca",
      email: "francesca.pasini@casastudente.demo",
      name: "Francesca Pasini",
      role: "landlord",
      passwordHash,
      verified: true,
      profileComplete: true,
      onboardingComplete: true,
      locale: "it",
      stripeAccountId: "acct_demo_francesca",
      createdAt: daysAgo(180, 14, 20),
      updatedAt: daysAgo(3, 12, 0),
    },
    {
      id: "user-landlord-matteo",
      email: "matteo.valentini@casastudente.demo",
      name: "Matteo Valentini",
      role: "landlord",
      passwordHash,
      verified: true,
      profileComplete: true,
      onboardingComplete: true,
      locale: "it",
      stripeAccountId: "acct_demo_matteo",
      createdAt: daysAgo(160, 10, 10),
      updatedAt: daysAgo(2, 9, 45),
    },
    {
      id: "user-admin-sara",
      email: "sara.conti@casastudente.demo",
      name: "Sara Conti",
      role: "admin",
      passwordHash,
      verified: true,
      profileComplete: true,
      onboardingComplete: true,
      locale: "it",
      createdAt: daysAgo(240, 8, 0),
      updatedAt: daysAgo(1, 8, 15),
    },
  ];

  await prisma.user.createMany({ data: users });

  const listings: Prisma.ListingCreateManyInput[] = [
    {
      id: "listing-centro-1",
      title: "Monolocale luminoso vicino a Piazza Saffi",
      address: "Via Giorgio Regnoli 18, Forlì",
      neighborhood: "Centro Storico",
      zone: "Centro Storico",
      type: "monolocale",
      price: 480,
      deposit: 960,
      utilities: "Condominio incluso, utenze escluse circa €70/mese",
      size: 34,
      rooms: 1,
      bathrooms: 1,
      floor: "2° con ascensore",
      availableFrom: "1 settembre 2026",
      status: "disponibile",
      verified: true,
      virtualTour: true,
      securePayments: true,
      furnished: true,
      photos: placeholderPhotos("Centro-Regnoli-Monolocale"),
      features: ["wi-fi fibra", "angolo cottura", "lavatrice", "aria condizionata", "posto bici interno"],
      description:
        "Ideale per una matricola che vuole muoversi a piedi tra centro, stazione e campus. Arredo recente, scrivania ampia e ottima luce naturale.",
      nearby: ["Piazza Saffi 4 min a piedi", "Campus di Forlì 9 min in bici", "Stazione FS 12 min a piedi"],
      latitude: 44.2226,
      longitude: 12.0412,
      landlordId: "user-landlord-francesca",
      createdAt: daysAgo(30, 9, 0),
      updatedAt: daysAgo(1, 9, 45),
    },
    {
      id: "listing-centro-2",
      title: "Stanza singola in appartamento condiviso con terrazzo",
      address: "Corso Garibaldi 84, Forlì",
      neighborhood: "Centro Storico",
      zone: "Centro Storico",
      type: "stanza_singola",
      price: 330,
      deposit: 660,
      utilities: "Wi-fi incluso, spese condominiali e utenze €85/mese",
      size: 18,
      rooms: 4,
      bathrooms: 2,
      floor: "3° senza ascensore",
      availableFrom: "15 settembre 2026",
      status: "disponibile",
      verified: true,
      virtualTour: true,
      securePayments: true,
      furnished: true,
      photos: placeholderPhotos("Centro-Garibaldi-Singola"),
      features: ["terrazzo", "lavastoviglie", "microonde", "doppia scrivania", "cantina bici"],
      description:
        "Camera ampia in casa mista studenti-lavoratori, atmosfera tranquilla e turni pulizie già organizzati.",
      nearby: ["Biblioteca Saffi 5 min a piedi", "Piazza del Duomo 6 min a piedi", "Supermercato 3 min"],
      latitude: 44.2231,
      longitude: 12.0434,
      landlordId: "user-landlord-francesca",
      createdAt: daysAgo(28, 10, 15),
      updatedAt: daysAgo(3, 18, 10),
    },
    {
      id: "listing-centro-3",
      title: "Bilocale ristrutturato con balcone interno",
      address: "Via delle Torri 9, Forlì",
      neighborhood: "Centro Storico",
      zone: "Centro Storico",
      type: "bilocale",
      price: 550,
      deposit: 1100,
      utilities: "Utenze autonome, stima €90/mese",
      size: 52,
      rooms: 2,
      bathrooms: 1,
      floor: "1° piano",
      availableFrom: "1 ottobre 2026",
      status: "in_trattativa",
      verified: true,
      virtualTour: true,
      securePayments: true,
      furnished: true,
      photos: placeholderPhotos("Centro-Torri-Bilocale"),
      features: ["balcone", "forno", "lavatrice", "armadio a muro", "porta blindata"],
      description:
        "Bilocale comodo per coppie di studenti magistrali o chi cerca indipendenza in pieno centro.",
      nearby: ["Piazza Ordelaffi 3 min a piedi", "Autobus linea 6 sotto casa", "Campus 11 min in bici"],
      latitude: 44.2238,
      longitude: 12.0396,
      landlordId: "user-landlord-francesca",
      createdAt: daysAgo(26, 11, 30),
      updatedAt: daysAgo(1, 16, 30),
    },
    {
      id: "listing-centro-4",
      title: "Stanza doppia per due amici a due passi dal centro",
      address: "Via Maroncelli 15, Forlì",
      neighborhood: "Centro Storico",
      zone: "Centro Storico",
      type: "stanza_doppia",
      price: 260,
      deposit: 520,
      utilities: "Spese tutto incluso €95/mese a persona",
      size: 24,
      rooms: 3,
      bathrooms: 1,
      floor: "2° piano",
      availableFrom: "1 settembre 2026",
      status: "disponibile",
      verified: true,
      virtualTour: false,
      securePayments: true,
      furnished: true,
      photos: placeholderPhotos("Centro-Maroncelli-Doppia"),
      features: ["due letti singoli", "scrivanie doppie", "wi-fi fibra", "cucina abitabile", "cantina"],
      description:
        "Soluzione economica e centrale perfetta per studenti Erasmus che arrivano insieme.",
      nearby: ["Centro storico 5 min a piedi", "Fermata bus per campus 2 min", "Palestra 6 min"],
      latitude: 44.2215,
      longitude: 12.0408,
      landlordId: "user-landlord-matteo",
      createdAt: daysAgo(24, 8, 30),
      updatedAt: daysAgo(5, 13, 0),
    },
    {
      id: "listing-centro-5",
      title: "Singola silenziosa in palazzo storico con studio condiviso",
      address: "Via Caterina Sforza 27, Forlì",
      neighborhood: "Centro Storico",
      zone: "Centro Storico",
      type: "stanza_singola",
      price: 345,
      deposit: 690,
      utilities: "Condominio incluso, utenze €80/mese",
      size: 16,
      rooms: 3,
      bathrooms: 2,
      floor: "1° piano",
      availableFrom: "20 settembre 2026",
      status: "in_trattativa",
      verified: true,
      virtualTour: true,
      securePayments: true,
      furnished: true,
      photos: placeholderPhotos("Centro-Sforza-Singola"),
      features: ["studio condiviso", "lavatrice", "wi-fi", "parquet", "cortile interno"],
      description:
        "Appartamento elegante e tranquillo, preferenza per studenti magistrali o tirocinanti.",
      nearby: ["Musei San Domenico 4 min", "Centro 6 min a piedi", "Stazione 15 min a piedi"],
      latitude: 44.2221,
      longitude: 12.0379,
      landlordId: "user-landlord-matteo",
      createdAt: daysAgo(19, 17, 10),
      updatedAt: daysAgo(2, 14, 20),
    },
    {
      id: "listing-universita-1",
      title: "Singola smart per studenti del campus universitario",
      address: "Via Corridoni 21, Forlì",
      neighborhood: "Zona Università",
      zone: "Zona Università",
      type: "stanza_singola",
      price: 315,
      deposit: 630,
      utilities: "Utenze e wi-fi €75/mese",
      size: 15,
      rooms: 4,
      bathrooms: 2,
      floor: "Terra rialzato",
      availableFrom: "1 settembre 2026",
      status: "affittato",
      verified: true,
      virtualTour: true,
      securePayments: true,
      furnished: true,
      photos: placeholderPhotos("Universita-Corridoni-Singola"),
      features: ["scrivania ergonomica", "fibra FTTH", "lavatrice", "climatizzazione", "deposito bici"],
      description:
        "Camera in appartamento da quattro studenti, gestione digitale delle spese e proprietaria molto presente.",
      nearby: ["Campus di Forlì 5 min a piedi", "Mensa universitaria 7 min", "Pista ciclabile per centro"],
      latitude: 44.2262,
      longitude: 12.0543,
      landlordId: "user-landlord-francesca",
      createdAt: daysAgo(40, 12, 0),
      updatedAt: daysAgo(7, 17, 15),
    },
    {
      id: "listing-universita-2",
      title: "Stanza singola con bagno quasi privato vicino al Teaching Hub",
      address: "Via Campo di Marte 48, Forlì",
      neighborhood: "Zona Università",
      zone: "Zona Università",
      type: "stanza_singola",
      price: 360,
      deposit: 720,
      utilities: "Tutto incluso €90/mese",
      size: 17,
      rooms: 3,
      bathrooms: 2,
      floor: "2° con ascensore",
      availableFrom: "10 settembre 2026",
      status: "disponibile",
      verified: true,
      virtualTour: true,
      securePayments: true,
      furnished: true,
      photos: placeholderPhotos("Universita-CampoMarte-Singola"),
      features: ["bagno adiacente", "smart tv", "lavastoviglie", "cantina bici", "tapparelle elettriche"],
      description:
        "Ottima soluzione per studenti internazionali che cercano un setup pronto all'uso.",
      nearby: ["Teaching Hub 6 min a piedi", "Parco Urbano 8 min in bici", "Supermercato 4 min"],
      latitude: 44.2251,
      longitude: 12.0561,
      landlordId: "user-landlord-francesca",
      createdAt: daysAgo(21, 9, 40),
      updatedAt: daysAgo(1, 11, 5),
    },
    {
      id: "listing-universita-3",
      title: "Monolocale compatto con cucinotto separato",
      address: "Via Lombardini 11, Forlì",
      neighborhood: "Zona Università",
      zone: "Zona Università",
      type: "monolocale",
      price: 440,
      deposit: 880,
      utilities: "Acqua inclusa, restante circa €70/mese",
      size: 30,
      rooms: 1,
      bathrooms: 1,
      floor: "1° piano",
      availableFrom: "1 ottobre 2026",
      status: "disponibile",
      verified: true,
      virtualTour: false,
      securePayments: true,
      furnished: true,
      photos: placeholderPhotos("Universita-Lombardini-Monolocale"),
      features: ["cucinotto separato", "forno", "divano letto", "lavatrice", "porta blindata"],
      description:
        "Soluzione indipendente per chi vuole vivere a piedi tra lezioni e biblioteca.",
      nearby: ["Campus 7 min a piedi", "Biblioteca Ruffilli 9 min", "Fermata bus linea 1"],
      latitude: 44.2248,
      longitude: 12.0535,
      landlordId: "user-landlord-matteo",
      createdAt: daysAgo(18, 15, 10),
      updatedAt: daysAgo(4, 10, 0),
    },
    {
      id: "listing-universita-4",
      title: "Doppia moderna per coppia di coinquilini internazionali",
      address: "Via Cesare Battisti 120, Forlì",
      neighborhood: "Zona Università",
      zone: "Zona Università",
      type: "stanza_doppia",
      price: 275,
      deposit: 550,
      utilities: "Utenze e internet €85/mese a persona",
      size: 22,
      rooms: 4,
      bathrooms: 2,
      floor: "3° piano",
      availableFrom: "1 settembre 2026",
      status: "disponibile",
      verified: true,
      virtualTour: true,
      securePayments: true,
      furnished: true,
      photos: placeholderPhotos("Universita-Battisti-Doppia"),
      features: ["due scrivanie", "cassaforte", "wi-fi", "lavatrice", "stendibiancheria interno"],
      description:
        "Camera doppia ben organizzata in appartamento internazionale a 10 minuti dal campus.",
      nearby: ["Campus 10 min a piedi", "Bar studenti 3 min", "Palestra universitaria 7 min"],
      latitude: 44.2271,
      longitude: 12.0509,
      landlordId: "user-landlord-matteo",
      createdAt: daysAgo(17, 13, 25),
      updatedAt: daysAgo(1, 18, 30),
    },
    {
      id: "listing-sanmartino-1",
      title: "Bilocale tranquillo con posto auto a San Martino",
      address: "Via Firenze 133, Forlì",
      neighborhood: "San Martino in Strada",
      zone: "San Martino in Strada",
      type: "bilocale",
      price: 500,
      deposit: 1000,
      utilities: "Autonome, posto auto incluso",
      size: 55,
      rooms: 2,
      bathrooms: 1,
      floor: "1° piano",
      availableFrom: "15 ottobre 2026",
      status: "disponibile",
      verified: true,
      virtualTour: true,
      securePayments: true,
      furnished: true,
      photos: placeholderPhotos("SanMartino-Firenze-Bilocale"),
      features: ["posto auto", "balcone", "cantina", "lavastoviglie", "climatizzatore"],
      description:
        "Perfetto per studenti che preferiscono tranquillità e spazio, con collegamento bus diretto per il centro.",
      nearby: ["Linea 92 per centro", "Supermercato 5 min in bici", "Tangenziale 4 min"],
      latitude: 44.2102,
      longitude: 12.0798,
      landlordId: "user-landlord-francesca",
      createdAt: daysAgo(32, 16, 20),
      updatedAt: daysAgo(3, 9, 15),
    },
    {
      id: "listing-sanmartino-2",
      title: "Singola spaziosa in villa con giardino condiviso",
      address: "Via Cervese 221, Forlì",
      neighborhood: "San Martino in Strada",
      zone: "San Martino in Strada",
      type: "stanza_singola",
      price: 295,
      deposit: 590,
      utilities: "Tutto incluso €80/mese",
      size: 16,
      rooms: 5,
      bathrooms: 2,
      floor: "Piano terra",
      availableFrom: "1 settembre 2026",
      status: "affittato",
      verified: true,
      virtualTour: false,
      securePayments: true,
      furnished: true,
      photos: placeholderPhotos("SanMartino-Cervese-Singola"),
      features: ["giardino", "posto bici", "lavatrice", "wi-fi", "scrivania 140 cm"],
      description:
        "Casa grande e conviviale con altri tre studenti e una giovane lavoratrice. Ideale per chi cerca verde e parcheggio facile.",
      nearby: ["Fermata bus 2 min", "Parco di quartiere 5 min", "Campus 14 min in bici"],
      latitude: 44.2097,
      longitude: 12.0819,
      landlordId: "user-landlord-matteo",
      createdAt: daysAgo(41, 10, 25),
      updatedAt: daysAgo(6, 12, 45),
    },
    {
      id: "listing-sanmartino-3",
      title: "Monolocale con ingresso indipendente e patio",
      address: "Via Minarda 42, Forlì",
      neighborhood: "San Martino in Strada",
      zone: "San Martino in Strada",
      type: "monolocale",
      price: 420,
      deposit: 840,
      utilities: "Autonome, media €65/mese",
      size: 29,
      rooms: 1,
      bathrooms: 1,
      floor: "Piano terra",
      availableFrom: "1 novembre 2026",
      status: "disponibile",
      verified: true,
      virtualTour: true,
      securePayments: true,
      furnished: true,
      photos: placeholderPhotos("SanMartino-Minarda-Monolocale"),
      features: ["ingresso indipendente", "patio", "lavatrice", "microonde", "armadio capiente"],
      description:
        "Mini appartamento raccolto e funzionale, ideale per chi vuole privacy e una zona più residenziale.",
      nearby: ["Fermata bus 4 min", "Alimentari 3 min", "Centro 12 min in bici"],
      latitude: 44.2134,
      longitude: 12.0756,
      landlordId: "user-landlord-francesca",
      createdAt: daysAgo(15, 14, 50),
      updatedAt: daysAgo(2, 10, 10),
    },
    {
      id: "listing-ronco-1",
      title: "Singola economica in appartamento bike friendly",
      address: "Via Decio Raggi 67, Forlì",
      neighborhood: "Ronco",
      zone: "Ronco",
      type: "stanza_singola",
      price: 285,
      deposit: 570,
      utilities: "Spese forfettarie €75/mese",
      size: 14,
      rooms: 4,
      bathrooms: 2,
      floor: "2° piano",
      availableFrom: "1 settembre 2026",
      status: "affittato",
      verified: true,
      virtualTour: false,
      securePayments: true,
      furnished: true,
      photos: placeholderPhotos("Ronco-Raggi-Singola"),
      features: ["posto bici coperto", "fibra", "lavatrice", "zanzariere", "scrivania"],
      description:
        "Ottimo prezzo per chi si muove in bici verso il campus o la stazione. Ambiente semplice ma curato.",
      nearby: ["Pista ciclabile 1 min", "Aeroporto 6 min in bici", "Centro 10 min in bici"],
      latitude: 44.2054,
      longitude: 12.0663,
      landlordId: "user-landlord-matteo",
      createdAt: daysAgo(38, 8, 50),
      updatedAt: daysAgo(7, 9, 0),
    },
    {
      id: "listing-ronco-2",
      title: "Bilocale moderno con cucina nuova e balcone",
      address: "Via Seganti 5, Forlì",
      neighborhood: "Ronco",
      zone: "Ronco",
      type: "bilocale",
      price: 510,
      deposit: 1020,
      utilities: "Autonome con caldaia nuova",
      size: 50,
      rooms: 2,
      bathrooms: 1,
      floor: "2° con ascensore",
      availableFrom: "20 ottobre 2026",
      status: "disponibile",
      verified: true,
      virtualTour: true,
      securePayments: true,
      furnished: true,
      photos: placeholderPhotos("Ronco-Seganti-Bilocale"),
      features: ["balcone", "cucina nuova", "lavastoviglie", "cantina", "videocitofono"],
      description:
        "Soluzione recente per chi vuole più privacy senza rinunciare a collegamenti rapidi verso il centro.",
      nearby: ["Aeroporto 5 min in auto", "Bus 3 min", "Centro 11 min in bici"],
      latitude: 44.2069,
      longitude: 12.0621,
      landlordId: "user-landlord-francesca",
      createdAt: daysAgo(22, 18, 0),
      updatedAt: daysAgo(1, 10, 35),
    },
    {
      id: "listing-ronco-3",
      title: "Doppia con balcone per studenti di infermieristica",
      address: "Via Isonzo 39, Forlì",
      neighborhood: "Ronco",
      zone: "Ronco",
      type: "stanza_doppia",
      price: 250,
      deposit: 500,
      utilities: "Tutto incluso €85/mese a persona",
      size: 23,
      rooms: 4,
      bathrooms: 2,
      floor: "1° piano",
      availableFrom: "5 settembre 2026",
      status: "disponibile",
      verified: true,
      virtualTour: true,
      securePayments: true,
      furnished: true,
      photos: placeholderPhotos("Ronco-Isonzo-Doppia"),
      features: ["balcone", "armadi doppi", "lavatrice", "wi-fi", "tavolo studio comune"],
      description:
        "Camera doppia ordinata e conveniente, perfetta per due amici che vogliono restare vicini all'ospedale e ben collegati al campus.",
      nearby: ["Ospedale 9 min in bici", "Bus diretto 4 min", "Parco di quartiere 3 min"],
      latitude: 44.2085,
      longitude: 12.0648,
      landlordId: "user-landlord-matteo",
      createdAt: daysAgo(20, 11, 5),
      updatedAt: daysAgo(2, 17, 0),
    },
    {
      id: "listing-vecchiazzano-1",
      title: "Monolocale silenzioso vicino all'ospedale Morgagni",
      address: "Viale dell'Appennino 203, Forlì",
      neighborhood: "Vecchiazzano",
      zone: "Vecchiazzano",
      type: "monolocale",
      price: 450,
      deposit: 900,
      utilities: "Riscaldamento centralizzato, utenze €75/mese",
      size: 31,
      rooms: 1,
      bathrooms: 1,
      floor: "2° piano",
      availableFrom: "1 settembre 2026",
      status: "in_trattativa",
      verified: true,
      virtualTour: true,
      securePayments: true,
      furnished: true,
      photos: placeholderPhotos("Vecchiazzano-Appennino-Monolocale"),
      features: ["aria condizionata", "lavatrice", "piastra induzione", "letto contenitore", "posto auto"],
      description:
        "Molto richiesto da specializzandi e tirocinanti grazie alla vicinanza all'ospedale e al contesto tranquillo.",
      nearby: ["Ospedale Morgagni 7 min a piedi", "Bus per centro 2 min", "Farmacia 3 min"],
      latitude: 44.2094,
      longitude: 12.0209,
      landlordId: "user-landlord-francesca",
      createdAt: daysAgo(25, 9, 20),
      updatedAt: daysAgo(1, 13, 10),
    },
    {
      id: "listing-vecchiazzano-2",
      title: "Bilocale ordinato con terrazzo e vista verde",
      address: "Via Castel Latino 28, Forlì",
      neighborhood: "Vecchiazzano",
      zone: "Vecchiazzano",
      type: "bilocale",
      price: 530,
      deposit: 1060,
      utilities: "Autonome, condominio incluso",
      size: 58,
      rooms: 2,
      bathrooms: 1,
      floor: "3° con ascensore",
      availableFrom: "1 ottobre 2026",
      status: "disponibile",
      verified: true,
      virtualTour: true,
      securePayments: true,
      furnished: true,
      photos: placeholderPhotos("Vecchiazzano-CastelLatino-Bilocale"),
      features: ["terrazzo", "cantina", "lavastoviglie", "forno", "scrivania extra"],
      description:
        "Bilocale completo per studenti di area sanitaria o giovani professionisti che cercano comfort e parcheggio facile.",
      nearby: ["Ospedale 8 min in bici", "Supermercato 5 min", "Centro 14 min in bici"],
      latitude: 44.2108,
      longitude: 12.0185,
      landlordId: "user-landlord-matteo",
      createdAt: daysAgo(14, 12, 40),
      updatedAt: daysAgo(2, 12, 0),
    },
    {
      id: "listing-vecchiazzano-3",
      title: "Singola con bagno condiviso in casa tranquilla",
      address: "Via del Bosco 14, Forlì",
      neighborhood: "Vecchiazzano",
      zone: "Vecchiazzano",
      type: "stanza_singola",
      price: 300,
      deposit: 600,
      utilities: "Spese fisse €70/mese",
      size: 15,
      rooms: 3,
      bathrooms: 1,
      floor: "Piano terra",
      availableFrom: "15 settembre 2026",
      status: "disponibile",
      verified: true,
      virtualTour: false,
      securePayments: true,
      furnished: true,
      photos: placeholderPhotos("Vecchiazzano-Bosco-Singola"),
      features: ["giardino", "wi-fi", "lavatrice", "scrivania", "armadio due ante"],
      description:
        "Ambiente molto silenzioso, ideale per chi studia medicina o cerca un contesto residenziale.",
      nearby: ["Fermata bus 4 min", "Ospedale 10 min in bici", "Parco 2 min"],
      latitude: 44.2122,
      longitude: 12.0234,
      landlordId: "user-landlord-francesca",
      createdAt: daysAgo(12, 16, 10),
      updatedAt: daysAgo(1, 9, 0),
    },
  ];

  await prisma.listing.createMany({ data: listings });

  await prisma.roommateProfile.createMany({
    data: [
      {
        id: "roommate-giulia",
        userId: "user-student-giulia",
        studyProgram: "Economia e Management",
        languages: ["it", "en"],
        budgetMin: 280,
        budgetMax: 420,
        sleepSchedule: "early",
        cleanliness: 5,
        socialPreference: "balanced",
        petTolerant: false,
        smokingTolerant: false,
        bio: "Cerco una casa ordinata, con coinquilini rispettosi e ritmi abbastanza regolari durante la settimana.",
        lookingForRoommate: true,
        preferredZones: ["Zona Università", "Centro Storico"],
        createdAt: daysAgo(34, 15, 0),
        updatedAt: daysAgo(2, 20, 10),
      },
      {
        id: "roommate-lukas",
        userId: "user-student-lukas",
        studyProgram: "Erasmus in Political Science",
        languages: ["en", "de", "it"],
        budgetMin: 300,
        budgetMax: 500,
        sleepSchedule: "flexible",
        cleanliness: 4,
        socialPreference: "social",
        petTolerant: true,
        smokingTolerant: false,
        bio: "I'm looking for an international flatshare with dinners together, good internet and enough desk space for project work.",
        lookingForRoommate: true,
        preferredZones: ["Zona Università", "Centro Storico", "Ronco"],
        createdAt: daysAgo(29, 10, 0),
        updatedAt: daysAgo(1, 18, 35),
      },
    ],
  });

  await prisma.journeyState.createMany({
    data: [
      {
        id: "journey-giulia",
        userId: "user-student-giulia",
        currentStage: "sign",
        completedSteps: ["profile", "saved-search", "tour-booking", "application"],
        startedAt: daysAgo(40, 9, 0),
        updatedAt: daysAgo(2, 11, 20),
      },
      {
        id: "journey-lukas",
        userId: "user-student-lukas",
        currentStage: "visit",
        completedSteps: ["profile", "verification", "roommate-profile"],
        startedAt: daysAgo(31, 13, 10),
        updatedAt: daysAgo(1, 16, 15),
      },
    ],
  });

  await prisma.onboardingProgress.createMany({
    data: [
      {
        id: "onboarding-giulia",
        userId: "user-student-giulia",
        currentStep: 5,
        completedSteps: ["account", "verification", "preferences", "roommate"],
        formData: asJson({ preferredBudget: 400, targetMoveIn: "2026-09-01", neighborhoods: ["Zona Università", "Centro Storico"] }),
        completedAt: daysAgo(20, 18, 0),
        createdAt: daysAgo(40, 9, 5),
        updatedAt: daysAgo(20, 18, 0),
      },
      {
        id: "onboarding-lukas",
        userId: "user-student-lukas",
        currentStep: 4,
        completedSteps: ["account", "verification", "preferences"],
        formData: asJson({ moveInMonth: "September", needsEnglishSupport: true, maxBudget: 500 }),
        createdAt: daysAgo(30, 12, 0),
        updatedAt: daysAgo(1, 15, 40),
      },
    ],
  });

  await prisma.document.createMany({
    data: [
      {
        id: "doc-giulia-id",
        userId: "user-student-giulia",
        name: "Carta identità Giulia Bartoletti",
        type: "identity",
        fileUrl: "https://placehold.co/900x1200/png?text=CI+Giulia",
        fileKey: "documents/giulia-carta-identita",
        mimeType: "image/png",
        sizeBytes: 214000,
        verified: true,
        createdAt: daysAgo(39, 10, 0),
        updatedAt: daysAgo(39, 10, 0),
      },
      {
        id: "doc-giulia-iscrizione",
        userId: "user-student-giulia",
        name: "Certificato di iscrizione UniBo",
        type: "academic",
        fileUrl: "https://placehold.co/900x1200/png?text=Iscrizione+UniBo",
        fileKey: "documents/giulia-iscrizione-unibo",
        mimeType: "application/pdf",
        sizeBytes: 168000,
        verified: true,
        expiresAt: daysFromNow(180),
        createdAt: daysAgo(38, 9, 30),
        updatedAt: daysAgo(10, 11, 0),
      },
      {
        id: "doc-lukas-passport",
        userId: "user-student-lukas",
        name: "Passport Lukas Meyer",
        type: "identity",
        fileUrl: "https://placehold.co/900x1200/png?text=Passport+Lukas",
        fileKey: "documents/lukas-passport",
        mimeType: "application/pdf",
        sizeBytes: 245000,
        verified: true,
        expiresAt: daysFromNow(540),
        createdAt: daysAgo(28, 14, 20),
        updatedAt: daysAgo(5, 10, 10),
      },
      {
        id: "doc-francesca-visura",
        userId: "user-landlord-francesca",
        name: "Visura catastale Via Corridoni 21",
        type: "property",
        fileUrl: "https://placehold.co/900x1200/png?text=Visura+Corridoni",
        fileKey: "documents/francesca-visura-corridoni",
        mimeType: "application/pdf",
        sizeBytes: 198000,
        verified: true,
        createdAt: daysAgo(120, 9, 0),
        updatedAt: daysAgo(20, 9, 0),
      },
    ],
  });

  await prisma.uploadedFile.createMany({
    data: [
      {
        id: "file-listing-centro-1-cover",
        userId: "user-landlord-francesca",
        listingId: "listing-centro-1",
        fileName: "centro-regnoli-cover.png",
        fileKey: "listing_photo/centro-regnoli-cover",
        fileUrl: placeholderPhotos("Centro-Regnoli-Monolocale")[0],
        mimeType: "image/png",
        sizeBytes: 310000,
        category: "listing_photo",
        createdAt: daysAgo(30, 9, 5),
      },
      {
        id: "file-listing-uni-2-cover",
        userId: "user-landlord-francesca",
        listingId: "listing-universita-2",
        fileName: "campo-di-marte-cover.png",
        fileKey: "listing_photo/campo-di-marte-cover",
        fileUrl: placeholderPhotos("Universita-CampoMarte-Singola")[0],
        mimeType: "image/png",
        sizeBytes: 295000,
        category: "listing_photo",
        createdAt: daysAgo(21, 9, 45),
      },
      {
        id: "file-listing-ronco-2-cover",
        userId: "user-landlord-francesca",
        listingId: "listing-ronco-2",
        fileName: "ronco-seganti-cover.png",
        fileKey: "listing_photo/ronco-seganti-cover",
        fileUrl: placeholderPhotos("Ronco-Seganti-Bilocale")[0],
        mimeType: "image/png",
        sizeBytes: 322000,
        category: "listing_photo",
        createdAt: daysAgo(22, 18, 5),
      },
      {
        id: "file-lukas-passport-copy",
        userId: "user-student-lukas",
        fileName: "lukas-passport-copy.pdf",
        fileKey: "document/lukas-passport-copy",
        fileUrl: "https://placehold.co/900x1200/png?text=Lukas+Passport+Copy",
        mimeType: "application/pdf",
        sizeBytes: 210400,
        category: "document",
        createdAt: daysAgo(28, 14, 25),
      },
    ],
  });

  await prisma.housingGroup.createMany({
    data: [
      {
        id: "group-casa-campus-2026",
        name: "Casa Campus 2026",
        description: "Gruppo per trovare un appartamento condiviso vicino al Campus con budget medio e regole chiare sulle pulizie.",
        maxMembers: 4,
        budget: 420,
        targetZones: ["Zona Università", "Centro Storico"],
        status: "searching",
        createdAt: daysAgo(21, 19, 15),
        updatedAt: daysAgo(1, 18, 20),
      },
      {
        id: "group-ronco-bike-house",
        name: "Ronco Bike House",
        description: "Mini gruppo orientato a case in zona Ronco con posto bici e costi contenuti.",
        maxMembers: 3,
        budget: 350,
        targetZones: ["Ronco", "San Martino in Strada"],
        status: "forming",
        createdAt: daysAgo(18, 12, 0),
        updatedAt: daysAgo(3, 17, 0),
      },
    ],
  });

  await prisma.housingGroupMember.createMany({
    data: [
      {
        id: "group-member-giulia-campus",
        groupId: "group-casa-campus-2026",
        userId: "user-student-giulia",
        role: "admin",
        joinedAt: daysAgo(21, 19, 20),
      },
      {
        id: "group-member-lukas-campus",
        groupId: "group-casa-campus-2026",
        userId: "user-student-lukas",
        role: "member",
        joinedAt: daysAgo(19, 13, 45),
      },
      {
        id: "group-member-lukas-ronco",
        groupId: "group-ronco-bike-house",
        userId: "user-student-lukas",
        role: "admin",
        joinedAt: daysAgo(18, 12, 5),
      },
    ],
  });

  const conversations: Prisma.ConversationCreateManyInput[] = [
    {
      id: "conversation-giulia-corridoni",
      listingId: "listing-universita-1",
      lastMessage: "Grazie, passo domani alle 17:30 per vedere la stanza.",
      lastMessageAt: daysAgo(1, 18, 42),
      createdAt: daysAgo(7, 10, 5),
    },
    {
      id: "conversation-lukas-campo-di-marte",
      listingId: "listing-universita-2",
      lastMessage: "Yes, utilities are fixed at 90 euro per month and the room is available from 10 September.",
      lastMessageAt: daysAgo(2, 11, 15),
      createdAt: daysAgo(6, 14, 20),
    },
    {
      id: "conversation-giulia-seganti",
      listingId: "listing-ronco-2",
      lastMessage: "Il proprietario può inviare la bozza del 4+4 entro venerdì.",
      lastMessageAt: daysAgo(4, 17, 25),
      createdAt: daysAgo(9, 9, 0),
    },
    {
      id: "conversation-lukas-vecchiazzano",
      listingId: "listing-vecchiazzano-1",
      lastMessage: "Ti mando volentieri il virtual tour e il video del quartiere.",
      lastMessageAt: daysAgo(3, 16, 55),
      createdAt: daysAgo(8, 16, 40),
    },
  ];

  await prisma.conversation.createMany({ data: conversations });

  await prisma.conversationUser.createMany({
    data: [
      { id: "cu-giulia-corridoni-student", conversationId: "conversation-giulia-corridoni", userId: "user-student-giulia", unreadCount: 0 },
      { id: "cu-giulia-corridoni-landlord", conversationId: "conversation-giulia-corridoni", userId: "user-landlord-francesca", unreadCount: 1 },
      { id: "cu-lukas-campo-student", conversationId: "conversation-lukas-campo-di-marte", userId: "user-student-lukas", unreadCount: 0 },
      { id: "cu-lukas-campo-landlord", conversationId: "conversation-lukas-campo-di-marte", userId: "user-landlord-francesca", unreadCount: 0 },
      { id: "cu-giulia-seganti-student", conversationId: "conversation-giulia-seganti", userId: "user-student-giulia", unreadCount: 2 },
      { id: "cu-giulia-seganti-landlord", conversationId: "conversation-giulia-seganti", userId: "user-landlord-matteo", unreadCount: 0 },
      { id: "cu-lukas-vecchiazzano-student", conversationId: "conversation-lukas-vecchiazzano", userId: "user-student-lukas", unreadCount: 0 },
      { id: "cu-lukas-vecchiazzano-landlord", conversationId: "conversation-lukas-vecchiazzano", userId: "user-landlord-francesca", unreadCount: 0 },
    ],
  });

  await prisma.message.createMany({
    data: [
      {
        id: "msg-1",
        conversationId: "conversation-giulia-corridoni",
        senderId: "user-student-giulia",
        content: "Ciao Francesca, la stanza in Via Corridoni è ancora disponibile per settembre?",
        read: true,
        createdAt: daysAgo(7, 10, 8),
      },
      {
        id: "msg-2",
        conversationId: "conversation-giulia-corridoni",
        senderId: "user-landlord-francesca",
        content: "Ciao Giulia, sì, si libera il 1 settembre ed è già pronta per entrare.",
        read: true,
        createdAt: daysAgo(7, 10, 20),
      },
      {
        id: "msg-3",
        conversationId: "conversation-giulia-corridoni",
        senderId: "user-student-giulia",
        content: "Perfetto, posso passare domani pomeriggio?",
        read: true,
        createdAt: daysAgo(1, 18, 10),
      },
      {
        id: "msg-4",
        conversationId: "conversation-giulia-corridoni",
        senderId: "user-landlord-francesca",
        content: "Certo, ti aspetto alle 17:30. Ti lascio anche il portone aperto per il sopralluogo veloce.",
        read: false,
        createdAt: daysAgo(1, 18, 42),
      },
      {
        id: "msg-5",
        conversationId: "conversation-lukas-campo-di-marte",
        senderId: "user-student-lukas",
        content: "Hi Francesca, is the room suitable for an Erasmus student staying until February?",
        translatedContent: "Ciao Francesca, la stanza è adatta a uno studente Erasmus che resta fino a febbraio?",
        read: true,
        createdAt: daysAgo(6, 14, 22),
      },
      {
        id: "msg-6",
        conversationId: "conversation-lukas-campo-di-marte",
        senderId: "user-landlord-francesca",
        content: "Yes, a transitory contract is possible. The flatmates also speak English.",
        translatedContent: "Sì, è possibile un contratto transitorio. Anche gli altri coinquilini parlano inglese.",
        read: true,
        createdAt: daysAgo(6, 14, 40),
      },
      {
        id: "msg-7",
        conversationId: "conversation-lukas-campo-di-marte",
        senderId: "user-student-lukas",
        content: "Great, could you confirm if utilities are fixed?",
        translatedContent: "Perfetto, puoi confermare se le utenze sono a forfait?",
        read: true,
        createdAt: daysAgo(2, 10, 55),
      },
      {
        id: "msg-8",
        conversationId: "conversation-lukas-campo-di-marte",
        senderId: "user-landlord-francesca",
        content: "Yes, utilities are fixed at 90 euro per month and the room is available from 10 September.",
        translatedContent: "Sì, le utenze sono fisse a 90 euro al mese e la stanza è disponibile dal 10 settembre.",
        read: true,
        createdAt: daysAgo(2, 11, 15),
      },
      {
        id: "msg-9",
        conversationId: "conversation-giulia-seganti",
        senderId: "user-student-giulia",
        content: "Buongiorno Matteo, il bilocale di Ronco è adatto anche a un contratto 4+4?",
        read: true,
        createdAt: daysAgo(9, 9, 5),
      },
      {
        id: "msg-10",
        conversationId: "conversation-giulia-seganti",
        senderId: "user-landlord-matteo",
        content: "Sì, per profili solidi posso proporre sia transitorio sia 4+4 con cedolare secca.",
        read: true,
        createdAt: daysAgo(9, 9, 18),
      },
      {
        id: "msg-11",
        conversationId: "conversation-giulia-seganti",
        senderId: "user-landlord-matteo",
        content: "Ti mando la bozza del 4+4 con canone bloccato e possibilità di recesso agevolato al secondo anno.",
        read: false,
        createdAt: daysAgo(4, 17, 25),
      },
      {
        id: "msg-12",
        conversationId: "conversation-lukas-vecchiazzano",
        senderId: "user-student-lukas",
        content: "Ciao, il quartiere di Vecchiazzano è ben collegato al campus?",
        translatedContent: "Hi, is Vecchiazzano well connected to the campus?",
        read: true,
        createdAt: daysAgo(8, 16, 42),
      },
      {
        id: "msg-13",
        conversationId: "conversation-lukas-vecchiazzano",
        senderId: "user-landlord-francesca",
        content: "Sì, c'è il bus diretto e in bici ci vogliono circa 15 minuti. Ti mando anche il video del percorso.",
        translatedContent: "Yes, there is a direct bus and by bike it takes around 15 minutes. I'll send you a video of the route too.",
        read: true,
        createdAt: daysAgo(8, 17, 5),
      },
      {
        id: "msg-14",
        conversationId: "conversation-lukas-vecchiazzano",
        senderId: "user-landlord-francesca",
        content: "Ti mando volentieri il virtual tour e il video del quartiere.",
        translatedContent: "Happy to send the virtual tour and a video of the neighborhood.",
        read: true,
        createdAt: daysAgo(3, 16, 55),
      },
    ],
  });

  await prisma.review.createMany({
    data: [
      {
        id: "review-1",
        reviewerId: "user-student-giulia",
        revieweeId: "user-landlord-francesca",
        listingId: "listing-universita-1",
        ratingOverall: 5,
        ratingCleanliness: 5,
        ratingCommunication: 5,
        ratingAccuracy: 4,
        ratingValue: 5,
        comment: "Francesca risponde velocemente e la casa era esattamente come nelle foto. Perfetta per iniziare l'anno accademico senza stress.",
        verifiedLease: true,
        flagged: false,
        createdAt: daysAgo(12, 19, 0),
      },
      {
        id: "review-2",
        reviewerId: "user-student-lukas",
        revieweeId: "user-landlord-francesca",
        listingId: "listing-universita-2",
        ratingOverall: 5,
        ratingCleanliness: 5,
        ratingCommunication: 5,
        ratingAccuracy: 5,
        ratingValue: 4,
        comment: "Molto utile per studenti Erasmus: inglese chiaro, check-in semplice e appartamento davvero pronto all'uso.",
        verifiedLease: true,
        flagged: false,
        createdAt: daysAgo(11, 18, 20),
      },
      {
        id: "review-3",
        reviewerId: "user-student-giulia",
        revieweeId: "user-landlord-matteo",
        listingId: "listing-ronco-2",
        ratingOverall: 4,
        ratingCleanliness: 4,
        ratingCommunication: 5,
        ratingAccuracy: 4,
        ratingValue: 4,
        comment: "Bilocale ben tenuto e proprietario disponibile nel chiarire le clausole contrattuali. Quartiere tranquillo.",
        verifiedLease: false,
        flagged: false,
        createdAt: daysAgo(10, 21, 15),
      },
      {
        id: "review-4",
        reviewerId: "user-student-lukas",
        revieweeId: "user-landlord-matteo",
        listingId: "listing-centro-4",
        ratingOverall: 4,
        ratingCleanliness: 4,
        ratingCommunication: 4,
        ratingAccuracy: 4,
        ratingValue: 5,
        comment: "Prezzo onesto e zona comodissima. La doppia è semplice ma molto funzionale per due studenti.",
        verifiedLease: false,
        flagged: false,
        createdAt: daysAgo(9, 20, 35),
      },
      {
        id: "review-5",
        reviewerId: "user-student-giulia",
        revieweeId: "user-landlord-francesca",
        listingId: "listing-centro-1",
        ratingOverall: 5,
        ratingCleanliness: 5,
        ratingCommunication: 5,
        ratingAccuracy: 5,
        ratingValue: 4,
        comment: "Monolocale davvero luminoso e molto silenzioso nonostante il centro. Ottimo per preparare esami.",
        verifiedLease: true,
        flagged: false,
        createdAt: daysAgo(8, 12, 10),
      },
      {
        id: "review-6",
        reviewerId: "user-student-lukas",
        revieweeId: "user-landlord-francesca",
        listingId: "listing-vecchiazzano-1",
        ratingOverall: 4,
        ratingCleanliness: 5,
        ratingCommunication: 4,
        ratingAccuracy: 4,
        ratingValue: 4,
        comment: "Quartiere molto calmo e ben collegato. Ottima soluzione per chi frequenta l'ospedale o cerca silenzio.",
        verifiedLease: false,
        flagged: false,
        createdAt: daysAgo(7, 13, 25),
      },
      {
        id: "review-7",
        reviewerId: "user-landlord-francesca",
        revieweeId: "user-student-giulia",
        listingId: "listing-universita-1",
        ratingOverall: 5,
        ratingCleanliness: 5,
        ratingCommunication: 5,
        ratingAccuracy: 5,
        ratingValue: 5,
        comment: "Giulia è stata puntualissima con i pagamenti e molto rispettosa degli spazi comuni. Profilo ideale.",
        verifiedLease: true,
        flagged: false,
        createdAt: daysAgo(6, 9, 10),
      },
      {
        id: "review-8",
        reviewerId: "user-landlord-matteo",
        revieweeId: "user-student-lukas",
        listingId: "listing-centro-4",
        ratingOverall: 4,
        ratingCleanliness: 4,
        ratingCommunication: 5,
        ratingAccuracy: 4,
        ratingValue: 4,
        comment: "Lukas è molto educato e organizzato, utile anche nella comunicazione con coinquilini internazionali.",
        verifiedLease: true,
        flagged: false,
        createdAt: daysAgo(5, 18, 45),
      },
      {
        id: "review-9",
        reviewerId: "user-landlord-francesca",
        revieweeId: "user-student-lukas",
        listingId: "listing-universita-2",
        ratingOverall: 5,
        ratingCleanliness: 4,
        ratingCommunication: 5,
        ratingAccuracy: 5,
        ratingValue: 5,
        comment: "Studente affidabile, ha inviato subito i documenti Erasmus e gestisce bene la vita in condivisione.",
        verifiedLease: true,
        flagged: false,
        createdAt: daysAgo(4, 10, 5),
      },
      {
        id: "review-10",
        reviewerId: "user-landlord-matteo",
        revieweeId: "user-student-giulia",
        listingId: "listing-ronco-2",
        ratingOverall: 5,
        ratingCleanliness: 5,
        ratingCommunication: 4,
        ratingAccuracy: 5,
        ratingValue: 4,
        comment: "Molto precisa nelle visite e nelle richieste contrattuali, profilo con forte attenzione ai dettagli.",
        verifiedLease: false,
        flagged: false,
        createdAt: daysAgo(3, 12, 0),
      },
      {
        id: "review-11",
        reviewerId: "user-student-giulia",
        revieweeId: "user-landlord-matteo",
        listingId: "listing-sanmartino-2",
        ratingOverall: 4,
        ratingCleanliness: 4,
        ratingCommunication: 4,
        ratingAccuracy: 4,
        ratingValue: 5,
        comment: "Casa conviviale e verde, ottima per chi vuole spendere meno senza rinunciare agli spazi comuni.",
        verifiedLease: true,
        flagged: false,
        createdAt: daysAgo(2, 21, 0),
      },
      {
        id: "review-12",
        reviewerId: "user-student-lukas",
        revieweeId: "user-landlord-francesca",
        listingId: "listing-centro-3",
        ratingOverall: 5,
        ratingCleanliness: 5,
        ratingCommunication: 5,
        ratingAccuracy: 4,
        ratingValue: 4,
        comment: "Appartamento davvero ben ristrutturato e quartiere comodissimo. Ottimo supporto anche per chi non parla ancora bene italiano.",
        verifiedLease: false,
        flagged: false,
        createdAt: daysAgo(1, 20, 10),
      },
    ],
  });

  await prisma.leaseContract.createMany({
    data: [
      {
        id: "lease-giulia-corridoni",
        tenantId: "user-student-giulia",
        landlordId: "user-landlord-francesca",
        listingId: "listing-universita-1",
        address: "Via Corridoni 21, Forlì",
        monthlyRent: 315,
        deposit: 630,
        startDate: new Date("2026-09-01T00:00:00.000Z"),
        endDate: new Date("2027-08-31T00:00:00.000Z"),
        contractType: "transitorio",
        taxRegime: "cedolare_secca",
        status: "active",
        createdAt: daysAgo(20, 11, 0),
        updatedAt: daysAgo(1, 12, 5),
      },
      {
        id: "lease-lukas-campo-di-marte",
        tenantId: "user-student-lukas",
        landlordId: "user-landlord-francesca",
        listingId: "listing-universita-2",
        address: "Via Campo di Marte 48, Forlì",
        monthlyRent: 360,
        deposit: 720,
        startDate: new Date("2026-09-10T00:00:00.000Z"),
        endDate: new Date("2027-02-28T00:00:00.000Z"),
        contractType: "transitorio",
        taxRegime: "cedolare_secca",
        status: "pending_signature",
        createdAt: daysAgo(12, 15, 20),
        updatedAt: daysAgo(2, 11, 20),
      },
      {
        id: "lease-giulia-centro-legacy",
        tenantId: "user-student-giulia",
        landlordId: "user-landlord-matteo",
        listingId: "listing-centro-3",
        address: "Via delle Torri 9, Forlì",
        monthlyRent: 540,
        deposit: 1080,
        startDate: new Date("2024-09-01T00:00:00.000Z"),
        endDate: new Date("2028-08-31T00:00:00.000Z"),
        contractType: "quattro_piu_quattro",
        taxRegime: "ordinario",
        status: "active",
        createdAt: daysAgo(300, 9, 0),
        updatedAt: daysAgo(4, 14, 0),
      },
      {
        id: "lease-lukas-centro-double",
        tenantId: "user-student-lukas",
        landlordId: "user-landlord-matteo",
        listingId: "listing-centro-4",
        address: "Via Maroncelli 15, Forlì",
        monthlyRent: 260,
        deposit: 520,
        startDate: new Date("2026-09-05T00:00:00.000Z"),
        endDate: new Date("2027-06-30T00:00:00.000Z"),
        contractType: "transitorio",
        taxRegime: "cedolare_secca",
        status: "draft",
        createdAt: daysAgo(8, 18, 0),
        updatedAt: daysAgo(3, 16, 50),
      },
    ],
  });

  await prisma.payment.createMany({
    data: [
      {
        id: "payment-1",
        payerId: "user-student-giulia",
        recipientId: "user-landlord-francesca",
        listingId: "listing-universita-1",
        amount: 630,
        platformFee: 18,
        type: "deposit",
        status: "completed",
        month: "settembre 2026",
        receiptNumber: "CS-DEP-2026-001",
        stripePaymentId: "pi_demo_001",
        stripeSessionId: "cs_demo_001",
        createdAt: daysAgo(15, 10, 0),
      },
      {
        id: "payment-2",
        payerId: "user-student-giulia",
        recipientId: "user-landlord-francesca",
        listingId: "listing-universita-1",
        amount: 315,
        platformFee: 9,
        type: "rent",
        status: "completed",
        month: "settembre 2026",
        receiptNumber: "CS-REN-2026-001",
        stripePaymentId: "pi_demo_002",
        stripeSessionId: "cs_demo_002",
        createdAt: daysAgo(5, 9, 10),
      },
      {
        id: "payment-3",
        payerId: "user-student-lukas",
        recipientId: "user-landlord-francesca",
        listingId: "listing-universita-2",
        amount: 720,
        platformFee: 20,
        type: "deposit",
        status: "pending",
        month: "settembre 2026",
        stripePaymentId: "pi_demo_003",
        stripeSessionId: "cs_demo_003",
        createdAt: daysAgo(2, 11, 30),
      },
      {
        id: "payment-4",
        payerId: "user-student-lukas",
        recipientId: "user-landlord-francesca",
        listingId: "listing-universita-2",
        amount: 360,
        platformFee: 10,
        type: "rent",
        status: "pending",
        month: "ottobre 2026",
        stripePaymentId: "pi_demo_004",
        stripeSessionId: "cs_demo_004",
        createdAt: daysAgo(2, 11, 35),
      },
      {
        id: "payment-5",
        payerId: "user-student-giulia",
        recipientId: "user-landlord-matteo",
        listingId: "listing-centro-3",
        amount: 540,
        platformFee: 12,
        type: "rent",
        status: "completed",
        month: "luglio 2026",
        receiptNumber: "CS-REN-2026-015",
        stripePaymentId: "pi_demo_005",
        stripeSessionId: "cs_demo_005",
        createdAt: daysAgo(35, 9, 30),
      },
      {
        id: "payment-6",
        payerId: "user-student-giulia",
        recipientId: "user-landlord-matteo",
        listingId: "listing-centro-3",
        amount: 540,
        platformFee: 12,
        type: "rent",
        status: "completed",
        month: "agosto 2026",
        receiptNumber: "CS-REN-2026-016",
        stripePaymentId: "pi_demo_006",
        stripeSessionId: "cs_demo_006",
        createdAt: daysAgo(5, 9, 35),
      },
      {
        id: "payment-7",
        payerId: "user-student-lukas",
        recipientId: "user-landlord-matteo",
        listingId: "listing-centro-4",
        amount: 260,
        platformFee: 8,
        type: "rent",
        status: "pending",
        month: "settembre 2026",
        stripePaymentId: "pi_demo_007",
        stripeSessionId: "cs_demo_007",
        createdAt: daysAgo(3, 16, 55),
      },
      {
        id: "payment-8",
        payerId: "user-student-giulia",
        recipientId: "user-landlord-francesca",
        listingId: "listing-universita-1",
        amount: 14.9,
        platformFee: 0,
        type: "insurance_premium",
        status: "completed",
        month: "settembre 2026",
        receiptNumber: "CS-INS-2026-001",
        stripePaymentId: "pi_demo_008",
        stripeSessionId: "cs_demo_008",
        createdAt: daysAgo(4, 8, 50),
      },
    ],
  });

  await prisma.savedSearch.createMany({
    data: [
      {
        id: "search-giulia-campus",
        userId: "user-student-giulia",
        name: "Vicino al Campus sotto €380",
        criteriaJson: asJson({ zones: ["Zona Università", "Centro Storico"], maxPrice: 380, types: ["stanza_singola"], furnished: true, virtualTour: true }),
        notifyEmail: true,
        notifyInApp: true,
        createdAt: daysAgo(24, 18, 0),
      },
      {
        id: "search-giulia-bilocale",
        userId: "user-student-giulia",
        name: "Bilocale con contratto 4+4",
        criteriaJson: asJson({ zones: ["Ronco", "Centro Storico"], minSize: 45, maxPrice: 550, types: ["bilocale"], contractType: "quattro_piu_quattro" }),
        notifyEmail: false,
        notifyInApp: true,
        createdAt: daysAgo(16, 12, 30),
      },
      {
        id: "search-lukas-erasmus",
        userId: "user-student-lukas",
        name: "Erasmus ready room",
        criteriaJson: asJson({ zones: ["Zona Università", "Centro Storico"], maxPrice: 500, types: ["stanza_singola", "monolocale"], englishFriendly: true, securePayments: true }),
        notifyEmail: true,
        notifyInApp: true,
        createdAt: daysAgo(14, 9, 10),
      },
      {
        id: "search-lukas-bike",
        userId: "user-student-lukas",
        name: "Casa con posto bici coperto",
        criteriaJson: asJson({ zones: ["Ronco", "San Martino in Strada"], maxPrice: 350, requiredFeatures: ["posto bici coperto", "wi-fi fibra"] }),
        notifyEmail: true,
        notifyInApp: false,
        createdAt: daysAgo(9, 19, 15),
      },
    ],
  });

  await prisma.communityPost.createMany({
    data: [
      {
        id: "post-1",
        userId: "user-admin-sara",
        type: "tip",
        title: "Come leggere un contratto transitorio a Forlì",
        content: "Abbiamo aggiornato la guida con esempi reali su durata, deposito, cedolare secca e clausole da controllare prima della firma.",
        tags: ["contratti", "guide", "forli"],
        likes: 28,
        createdAt: daysAgo(6, 9, 0),
      },
      {
        id: "post-2",
        userId: "user-student-giulia",
        type: "story",
        title: "La mia esperienza con una singola in Zona Università",
        content: "Ho trovato casa in 12 giorni usando alert e tour virtuali. Il consiglio migliore: chiedere sempre costi reali delle utenze prima della visita.",
        tags: ["esperienze", "zona-universita", "singola"],
        likes: 19,
        createdAt: daysAgo(5, 18, 15),
      },
      {
        id: "post-3",
        userId: "user-student-lukas",
        type: "question",
        title: "Qual è la zona migliore per un Erasmus senza auto?",
        content: "Sto scegliendo tra Centro e Zona Università. Mi interessa poter andare al campus in bici e avere supermercato vicino.",
        tags: ["erasmus", "quartieri", "mobilita"],
        likes: 14,
        createdAt: daysAgo(4, 13, 35),
      },
      {
        id: "post-4",
        userId: "user-landlord-francesca",
        type: "event",
        title: "Open house sabato pomeriggio in Via Campo di Marte",
        content: "Sabato dalle 15 alle 18 visite su prenotazione per due stanze disponibili. Portate documento e badge universitario.",
        tags: ["open-house", "visite", "campo-di-marte"],
        likes: 11,
        createdAt: daysAgo(3, 10, 45),
      },
      {
        id: "post-5",
        userId: "user-landlord-matteo",
        type: "tip",
        title: "Checklist rapida per coinquilini che vogliono vivere bene",
        content: "Condividere turni pulizie, spese chiare e regole sugli ospiti riduce quasi tutti i problemi entro il primo mese.",
        tags: ["coinquilini", "convivenza", "consigli"],
        likes: 17,
        createdAt: daysAgo(2, 8, 25),
      },
      {
        id: "post-6",
        userId: "user-admin-sara",
        type: "story",
        title: "Dati del mese: cresce la domanda di monolocali tra studenti internazionali",
        content: "Nelle ultime quattro settimane abbiamo registrato più richieste per monolocali arredati con tour virtuale e contratti transitori.",
        tags: ["insight", "studenti-internazionali", "monolocali"],
        likes: 23,
        createdAt: daysAgo(1, 9, 30),
      },
    ],
  });

  await prisma.tenantScore.createMany({
    data: [
      {
        id: "tenant-score-giulia",
        userId: "user-student-giulia",
        overallScore: 92,
        paymentHistory: 96,
        identityVerified: 100,
        rentalHistory: 88,
        incomeStability: 82,
        socialTrust: 90,
        academicStanding: 94,
        riskTier: "low",
        lastCalculated: daysAgo(2, 7, 30),
        createdAt: daysAgo(20, 7, 30),
        updatedAt: daysAgo(2, 7, 30),
      },
      {
        id: "tenant-score-lukas",
        userId: "user-student-lukas",
        overallScore: 87,
        paymentHistory: 84,
        identityVerified: 100,
        rentalHistory: 78,
        incomeStability: 81,
        socialTrust: 89,
        academicStanding: 90,
        riskTier: "low",
        lastCalculated: daysAgo(2, 7, 45),
        createdAt: daysAgo(12, 7, 45),
        updatedAt: daysAgo(2, 7, 45),
      },
    ],
  });

  await prisma.tourBooking.createMany({
    data: [
      {
        id: "tour-1",
        userId: "user-student-giulia",
        listingId: "listing-universita-1",
        type: "in_person",
        date: daysFromNow(1, 17, 30),
        status: "scheduled",
        notes: "Giulia arriverà in bici e chiede di vedere anche la cucina condivisa.",
        createdAt: daysAgo(1, 18, 43),
        updatedAt: daysAgo(1, 18, 43),
      },
      {
        id: "tour-2",
        userId: "user-student-lukas",
        listingId: "listing-universita-2",
        type: "virtual",
        date: daysFromNow(2, 18, 0),
        status: "scheduled",
        notes: "Meeting in inglese con link Zoom inviato via chat.",
        createdAt: daysAgo(2, 11, 20),
        updatedAt: daysAgo(2, 11, 20),
      },
      {
        id: "tour-3",
        userId: "user-student-giulia",
        listingId: "listing-ronco-2",
        type: "in_person",
        date: daysAgo(3, 17, 0),
        status: "completed",
        notes: "Visitato anche il vano bici e verificato il contratto 4+4.",
        createdAt: daysAgo(4, 10, 10),
        updatedAt: daysAgo(3, 19, 10),
      },
      {
        id: "tour-4",
        userId: "user-student-lukas",
        listingId: "listing-vecchiazzano-1",
        type: "virtual",
        date: daysAgo(2, 19, 0),
        status: "completed",
        notes: "Tour registrato e inviato in cloud con sottotitoli inglese.",
        createdAt: daysAgo(3, 16, 55),
        updatedAt: daysAgo(2, 19, 40),
      },
      {
        id: "tour-5",
        userId: "user-student-lukas",
        listingId: "listing-centro-4",
        type: "in_person",
        date: daysFromNow(4, 16, 15),
        status: "scheduled",
        notes: "Verrà con un amico interessato alla seconda postazione della doppia.",
        createdAt: daysAgo(1, 12, 50),
        updatedAt: daysAgo(1, 12, 50),
      },
    ],
  });

  await prisma.notification.createMany({
    data: [
      {
        id: "notification-1",
        userId: "user-student-giulia",
        type: "message",
        title: "Nuovo messaggio da Francesca Pasini",
        message: "La visita per Via Corridoni è confermata domani alle 17:30.",
        read: false,
        link: "/messages/conversation-giulia-corridoni",
        emailSent: true,
        pushSent: true,
        createdAt: daysAgo(1, 18, 43),
      },
      {
        id: "notification-2",
        userId: "user-student-giulia",
        type: "lease_reminder",
        title: "Firma contratto in arrivo",
        message: "Hai una bozza di contratto 4+4 pronta da revisionare per il bilocale di Ronco.",
        read: false,
        link: "/leases/lease-giulia-centro-legacy",
        emailSent: false,
        pushSent: true,
        createdAt: daysAgo(4, 17, 30),
      },
      {
        id: "notification-3",
        userId: "user-student-lukas",
        type: "group_invite",
        title: "Nuova attività nel gruppo Casa Campus 2026",
        message: "Giulia ha proposto una visita condivisa per due stanze in Zona Università.",
        read: true,
        link: "/groups/group-casa-campus-2026",
        emailSent: true,
        pushSent: true,
        createdAt: daysAgo(2, 9, 5),
      },
      {
        id: "notification-4",
        userId: "user-student-lukas",
        type: "payment",
        title: "Caparra da confermare",
        message: "La caparra per Via Campo di Marte è pronta per essere autorizzata in piattaforma.",
        read: false,
        link: "/payments/payment-3",
        emailSent: true,
        pushSent: true,
        createdAt: daysAgo(2, 11, 40),
      },
      {
        id: "notification-5",
        userId: "user-landlord-francesca",
        type: "availability",
        title: "Nuova visita prenotata",
        message: "Giulia Bartoletti visiterà la stanza di Via Corridoni domani alle 17:30.",
        read: false,
        link: "/landlord/tours/tour-1",
        emailSent: true,
        pushSent: true,
        createdAt: daysAgo(1, 18, 44),
      },
      {
        id: "notification-6",
        userId: "user-landlord-francesca",
        type: "message",
        title: "Messaggio tradotto automaticamente",
        message: "Lukas Meyer ha chiesto dettagli sulle utenze della stanza in Via Campo di Marte.",
        read: true,
        link: "/messages/conversation-lukas-campo-di-marte",
        emailSent: false,
        pushSent: true,
        createdAt: daysAgo(2, 11, 16),
      },
      {
        id: "notification-7",
        userId: "user-landlord-matteo",
        type: "review",
        title: "Nuova recensione ricevuta",
        message: "Giulia ha lasciato una recensione sul bilocale di Ronco.",
        read: true,
        link: "/reviews/review-3",
        emailSent: true,
        pushSent: false,
        createdAt: daysAgo(10, 21, 20),
      },
      {
        id: "notification-8",
        userId: "user-landlord-matteo",
        type: "payment",
        title: "Pagamento in attesa",
        message: "Il canone di settembre per la doppia in Via Maroncelli è in stato pending.",
        read: false,
        link: "/payments/payment-7",
        emailSent: true,
        pushSent: true,
        createdAt: daysAgo(3, 16, 56),
      },
      {
        id: "notification-9",
        userId: "user-admin-sara",
        type: "verification",
        title: "Nuovo documento verificato",
        message: "Il passaporto di Lukas Meyer è stato validato per i contratti Erasmus.",
        read: true,
        link: "/admin/verifications/doc-lukas-passport",
        emailSent: false,
        pushSent: false,
        createdAt: daysAgo(5, 10, 15),
      },
      {
        id: "notification-10",
        userId: "user-admin-sara",
        type: "system",
        title: "Picco ricerche monolocali",
        message: "Nelle ultime 24 ore le ricerche di monolocali tra €420 e €500 sono cresciute del 18%.",
        read: false,
        link: "/admin/insights",
        emailSent: false,
        pushSent: true,
        createdAt: daysAgo(1, 8, 20),
      },
      {
        id: "notification-11",
        userId: "user-student-giulia",
        type: "new_listing",
        title: "Nuovo annuncio compatibile con la tua ricerca",
        message: "È disponibile una singola in Centro Storico con budget in linea al tuo alert.",
        read: true,
        link: "/listings/listing-centro-5",
        emailSent: true,
        pushSent: true,
        createdAt: daysAgo(2, 8, 30),
      },
      {
        id: "notification-12",
        userId: "user-student-lukas",
        type: "availability",
        title: "Nuovo slot per tour virtuale",
        message: "Francesca ha aperto un tour virtuale extra per la stanza di Vecchiazzano.",
        read: false,
        link: "/tours/tour-4",
        emailSent: true,
        pushSent: true,
        createdAt: daysAgo(1, 11, 45),
      },
    ],
  });

  console.log(`✅ CasaStudente seed complete. Demo login password for all seeded users: ${DEMO_PASSWORD}`);
}

main()
  .catch((error) => {
    console.error("❌ CasaStudente seed failed", error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
